name: Build binary

on:
  workflow_dispatch:
  push:
    tags: 
      - '*'

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install -r requirements/requirements_dev.txt
        pip install pyinstaller

    - name: Build binary
      shell: bash
      run: |
        invoke build-binary

    - name: Test the binary
      shell: bash
      run: |
        invoke test-binary

    - name: Prepare binary for upload
      shell: bash
      run: |
        invoke prepare-binary
    
    - name: Upload release binaries
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./dist/*"]'

